### ISSUE TITLE
vagrant up failed due to TypeError on Mutagen.rb

### ISSUE THREAD

**Issue by 3150** [dasginganinja/vagrant-mutagen#8]
Hello.Thanks for your great plugin.

I tried to `vagrant up` with this plugin and I got error like this. 

[info]
- Mac OS 10.15.3
- Vagrant version is `2.2.14`

After downgrading vagrant version to 2.2.13, `vagrant up` is successfully finished.
I suppose it is related to this error. : https://github.com/agiledivider/vagrant-hostsupdater/issues/102

```
$ vagrant up

Bringing machine 'default' up with 'virtualbox' provider...
==> default: [vagrant-hostsupdater] Checking for host entries
==> default: [vagrant-hostsupdater]   found entry for: 192.168.50.10 sample-app
==> default: [vagrant-mutagen] Checking for SSH config entries
Traceback (most recent call last):
        29: from /opt/vagrant/embedded/gems/2.2.14/gems/vagrant-2.2.14/lib/vagrant/batch_action.rb:86:in `block (2 levels) in run'
        28: from /opt/vagrant/embedded/gems/2.2.14/gems/vagrant-2.2.14/lib/vagrant/machine.rb:201:in `action'
        27: from /opt/vagrant/embedded/gems/2.2.14/gems/vagrant-2.2.14/lib/vagrant/machine.rb:201:in `call'
        26: from /opt/vagrant/embedded/gems/2.2.14/gems/vagrant-2.2.14/lib/vagrant/environment.rb:613:in `lock'
        25: from /opt/vagrant/embedded/gems/2.2.14/gems/vagrant-2.2.14/lib/vagrant/machine.rb:215:in `block in action'
        24: from /opt/vagrant/embedded/gems/2.2.14/gems/vagrant-2.2.14/lib/vagrant/machine.rb:246:in `action_raw'
        23: from /opt/vagrant/embedded/gems/2.2.14/gems/vagrant-2.2.14/lib/vagrant/action/runner.rb:89:in `run'
        22: from /opt/vagrant/embedded/gems/2.2.14/gems/vagrant-2.2.14/lib/vagrant/util/busy.rb:19:in `busy'
        21: from /opt/vagrant/embedded/gems/2.2.14/gems/vagrant-2.2.14/lib/vagrant/action/runner.rb:89:in `block in run'
        20: from /opt/vagrant/embedded/gems/2.2.14/gems/vagrant-2.2.14/lib/vagrant/action/builder.rb:149:in `call'
        19: from /opt/vagrant/embedded/gems/2.2.14/gems/vagrant-2.2.14/lib/vagrant/action/warden.rb:48:in `call'
        18: from /opt/vagrant/embedded/gems/2.2.14/gems/vagrant-2.2.14/plugins/providers/virtualbox/action/check_virtualbox.rb:26:in `call'
        17: from /opt/vagrant/embedded/gems/2.2.14/gems/vagrant-2.2.14/lib/vagrant/action/warden.rb:48:in `call'
        16: from /opt/vagrant/embedded/gems/2.2.14/gems/vagrant-2.2.14/lib/vagrant/action/builtin/call.rb:43:in `call'
        15: from /opt/vagrant/embedded/gems/2.2.14/gems/vagrant-2.2.14/lib/vagrant/action/runner.rb:89:in `run'
        14: from /opt/vagrant/embedded/gems/2.2.14/gems/vagrant-2.2.14/lib/vagrant/util/busy.rb:19:in `busy'
        13: from /opt/vagrant/embedded/gems/2.2.14/gems/vagrant-2.2.14/lib/vagrant/action/runner.rb:89:in `block in run'
        12: from /opt/vagrant/embedded/gems/2.2.14/gems/vagrant-2.2.14/lib/vagrant/action/builder.rb:149:in `call'
        11: from /opt/vagrant/embedded/gems/2.2.14/gems/vagrant-2.2.14/lib/vagrant/action/warden.rb:48:in `call'
        10: from /opt/vagrant/embedded/gems/2.2.14/gems/vagrant-2.2.14/plugins/providers/virtualbox/action/created.rb:15:in `call'
         9: from /opt/vagrant/embedded/gems/2.2.14/gems/vagrant-2.2.14/lib/vagrant/action/warden.rb:48:in `call'
         8: from /opt/vagrant/embedded/gems/2.2.14/gems/vagrant-2.2.14/plugins/commands/up/middleware/store_box_metadata.rb:33:in `call'
         7: from /opt/vagrant/embedded/gems/2.2.14/gems/vagrant-2.2.14/lib/vagrant/action/warden.rb:48:in `call'
         6: from /Users/taka/.vagrant.d/gems/2.6.6/gems/vagrant-hostsupdater-1.2.1/lib/vagrant-hostsupdater/Action/UpdateHosts.rb:18:in `call'
         5: from /opt/vagrant/embedded/gems/2.2.14/gems/vagrant-2.2.14/lib/vagrant/action/warden.rb:48:in `call'
         4: from /Users/taka/.vagrant.d/gems/2.6.6/gems/vagrant-mutagen-0.1.2/lib/vagrant-mutagen/Action/UpdateConfig.rb:18:in `call'
         3: from /Users/taka/.vagrant.d/gems/2.6.6/gems/vagrant-mutagen-0.1.2/lib/vagrant-mutagen/Mutagen.rb:25:in `addConfigEntries'
         2: from /Users/taka/.vagrant.d/gems/2.6.6/gems/vagrant-mutagen-0.1.2/lib/vagrant-mutagen/Mutagen.rb:69:in `configEntryPattern'
         1: from /Users/taka/.vagrant.d/gems/2.6.6/gems/vagrant-mutagen-0.1.2/lib/vagrant-mutagen/Mutagen.rb:69:in `hexdigest'
/Users/taka/.vagrant.d/gems/2.6.6/gems/vagrant-mutagen-0.1.2/lib/vagrant-mutagen/Mutagen.rb:69:in `digest': no implicit conversion of nil into String (TypeError)
```

**Comment by gabriel-amaral** [comment]
@3150 on vagrant 2.2.14, they changed the way they call the plugins and the plugin is being called too early and the `machine.id` is not present yet. 

I created a PR https://github.com/dasginganinja/vagrant-mutagen/pull/9 that fixes this behavior.

**Comment by 3150** [comment]
Hi @gabriel-amaral Sorry for my late reply and thanks for the fix !
